### PR TITLE
pull request test

### LINKED ISSUE #1: Test Issue
I want this feature
Fix this bug

### PR DESCRIPTION
**Pull request by OlofSjogren**
closes #1

### CODE REVIEW

**Comment by ellawallinder** [comment]
Looks great!

**Comment by ideefiix** [comment]
Nice

**Review by OscarSanner — APPROVED** [review]
I think this looks great

**Review by ellawallinder — APPROVED** [review]
Great job!

**Review by ideefiix — APPROVED** [review]
Approved

**Review by pilhall — COMMENTED** [review]
nice!

**Pull request merged**
